version: '3'
services:
  listings-service:
    build: './listings-service'
    depends_on:
      - listings-service-db
    environment:
      - ./listings-service:/opt/app

  listings-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=db
    image: mysql:latest

  users-service:
    build: './users-service'
    depends_on:
      - users-service-db
    environment:
      - ./users-service:/opt/app

  users-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=db
    image: mysql:latest
